### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by efinkelb** [changhuixu/session-expiration-alert#3]
The link with the demo isn't working!

**Comment by changhuixu** [comment]
It is known that StackBlitz has issue with tsconfig relative path. I was waiting for StackBlitz to fix this issue since Angular 6. But maybe I missed something.

In order to make a demo site, I pushed a site to Netlify just now. Please check it out [Demo](https://session-expiration-alert.netlify.com/) .

Thank you.
